### ISSUE TITLE
ReferenceError: API_URL is not defined

### ISSUE THREAD

**Issue by Adrian8422** [walterARG2K/desafio-mod-6#1]
Hola Walter como va! Te comento. Estaba probando la app y resulta que cuando quiero ingresar a la sala con el segundo usuario me tira un error, debo clickar dos veces para que conecte con el usuario 1. 

![Correccion-walter-doble-click](https://user-images.githubusercontent.com/83373520/183311478-701ff67b-460a-4266-baac-ec52637060e9.png)

Luego de que con el usuario 1 presiono jugar quedo a la espera de que el usuario dos también presiono, lo cual cuando lo hago con el segundo usuario queda suspendido ambos lados y no avanza.

![walter-no-conecta-con-otro usuario](https://user-images.githubusercontent.com/83373520/183311498-c9d6109b-35c6-4850-9331-0496676533b1.png)

![image](https://user-images.githubusercontent.com/83373520/183311528-3cad94c3-bcd9-46c0-90d5-afbb4b1188a9.png)

Fijate que capaz no le esten llegando los datos bien al metodo del state. Saludos y éxitos con eso, cualquier cosa comunicate.

**Comment by walterortizz** [comment]
Hola Adrian, recién me fijo, el problema era que se me pasó eliminar la variable que hacía referencia al host de heroku.
podes darle otro vistazo y comentarme si ya te funciona correctamente, y gracias por tomarte el tiempo de mirar.

**Comment by Adrian8422** [comment]
Walter como va, ya no esta pasando lo del doble click. Pero fijate que en el momento en que ambos users seleccionan start para dar comienzo al juego,  este queda suspendido. No esta tomando la accion un user del otro. 
![no-conecta](https://user-images.githubusercontent.com/83373520/183327975-45bc6360-402a-476a-9bf3-ff3719542876.png)
Pegale una chequeda y cualquier cosita comunicalo. Saludos y éxitos !

**Comment by walterortizz** [comment]
Adrián, por lo que veo es porque usas el mismo navegador para ejecutar el juego, este tiene un guardado del nombre de usuario en el local storage, y eso causa que te tome solo un nombre de usuario, ejecutalo uno en esa misma pestaña y el otro en modo incógnito o en otro navegador y avisame.

**Comment by Adrian8422** [comment]
Buenas Walter, felicitaciones por terminarlo ! No percate lo del localstorage, lo acabo de probar y funciona correctamente. Un saludo y éxitos

**Comment by walterortizz** [comment]
Gracias por tomarte el tiempo Adrián.
