### ISSUE TITLE
desafio-6

### ISSUE THREAD

**Issue by ale-strada** [walterARG2K/desafio-mod-6#2]
Hola Walter! Probé la app y todo funciona bien hasta el momento de jugar. La primera vez que entre no me guardo el código de la sala y las otras veces que intente jugar se quedaba esperando a que el oponente presione jugar de ambos lados.

**Comment by walterortizz** [comment]
Hola Ale, puede que estés usando el mismo navegador y solo cambiando la pestaña? ya que el juego guarda el nombre del Usuario en el localstorage, intenta cambiar de navegador, o abrir en una pestaña normal, y la otra en incógnito y me avisas si te sigue corriendo el problema.

**Comment by ale-strada** [comment]
Ahhh. no me di cuenta de eso.. ya lo pruebo.

**Comment by ale-strada** [comment]
Lo probé con un jugador en incognito y si pude jugar. Funciona todo! Felicitaciones!

**Comment by walterortizz** [comment]
Gracias por tomarte el tiempo de mirar Ale.

**Comment by ale-strada** [comment]
@walterARG2K como va? me volvió a aparecer tu desafío en reviews, asiq ahora que puedo le doy al APROBAR. Saludos!
